name: Telebot Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: apt install -y pkg-config libcurl4-openssl-dev libjson-c-dev cmake binutils make
    - name: cmake 
      run: cmake .
    - name: make
      run: make
